name: mi_card_flutter
description: VPN App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Nossas dependÃªncias
  openvpn_flutter: ^1.1.1
  http: ^1.2.0
  device_info_plus: ^10.1.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
