name: Build Release (Ultra Light)

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v5
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      # GERA DOIS APKs PEQUENOS
      - name: Build APK (Release & Split)
        run: flutter build apk --release --split-per-abi

      # Upload para celulares novos (Maioria)
      - name: Upload APK Arm64 (Celulares Novos)
        uses: actions/upload-artifact@v4
        with:
          name: vpn-app-arm64
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      # Upload para celulares velhos
      - name: Upload APK ArmV7 (Celulares Antigos)
        uses: actions/upload-artifact@v4
        with:
          name: vpn-app-armv7
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
